function getMaterialPath(name){

  const paths = {

    // 転生0
    "スライムゼリー":   "img/materials/slimeGel.png",
    "キングゼリー":     "img/materials/kingGel.png",
    "ゴブリンの牙":     "img/materials/goblinTooth.png",
    "王族の牙":         "img/materials/kingTooth.png",
    "オークの皮":       "img/materials/orcSkin.png",
    "古代の皮":         "img/materials/ancientSkin.png",
    "竜のウロコ":       "img/materials/dragonScale.png",
    "紅竜の心臓":       "img/materials/dragonHeart.png",
    "狼の毛皮":         "img/materials/wolfFur.png",
    "銀の牙":           "img/materials/silverFang.png",
    "骨のかけら":       "img/materials/boneShard.png",
    "呪われた骨":       "img/materials/cursedBone.png",
    "コウモリの羽":     "img/materials/batWing.png",
    "漆黒の羽":         "img/materials/darkWing.png",
    "毒の鱗":           "img/materials/poisonScale.png",
    "猛毒の結晶":       "img/materials/poisonCrystal.png",
    "腐った肉":         "img/materials/rottenMeat.png",
    "呪いの心臓":       "img/materials/cursedHeart.png",
    "王の印章":         "img/materials/kingSeal.png",
    "黄金の王冠":       "img/materials/goldenCrown.png",

    // 転生1
    "氷の毛皮":         "img/materials/iceFur.png",
    "極寒の牙":         "img/materials/frostFang.png",
    "闇のエルフ耳":     "img/materials/darkElfEar.png",
    "呪われた弓":       "img/materials/cursedBow.png",
    "石の欠片":         "img/materials/stoneShard.png",
    "魔法石":           "img/materials/magicStone.png",
    "巨人の目玉":       "img/materials/giantEye.png",
    "魔眼の結晶":       "img/materials/magicEye.png",
    "ハーピーの羽":     "img/materials/harpyWing.png",
    "嵐の羽根":         "img/materials/stormFeather.png",
    "包帯の切れ端":     "img/materials/bandage.png",
    "呪いの包帯":       "img/materials/cursedBandage.png",
    "炎の結晶":         "img/materials/flameCrystal.png",
    "業火の核":         "img/materials/infernoCore.png",
    "錆びた鎧":         "img/materials/rustedArmor.png",
    "呪いの剣":         "img/materials/cursedSword.png",
    "海蛇の鱗":         "img/materials/seaScale.png",
    "深海の宝石":       "img/materials/deepGem.png",
    "氷竜のウロコ":     "img/materials/iceScale.png",
    "氷竜の心臓":       "img/materials/iceHeart.png",

    // 転生2
    "闇の鎧片":         "img/materials/darkArmorShard.png",
    "闇の剣":           "img/materials/darkSword.png",
    "石化の鱗":         "img/materials/petrifyScale.png",
    "石化の瞳":         "img/materials/petrifyEye.png",
    "獣人の爪":         "img/materials/beastClaw.png",
    "月の牙":           "img/materials/moonFang.png",
    "幽霊の布":         "img/materials/ghostCloth.png",
    "魂の結晶":         "img/materials/soulCrystal.png",
    "炎の皮":           "img/materials/flameSkin.png",
    "炎帝の核":         "img/materials/infernoEmperorCore.png",
    "牛の角":           "img/materials/bullHorn.png",
    "黄金の角":         "img/materials/goldenHorn.png",
    "蛇の髪":           "img/materials/snakeHair.png",
    "石化の眼":         "img/materials/petrifyGaze.png",
    "吸血鬼の牙":       "img/materials/vampireFang.png",
    "血の宝石":         "img/materials/bloodGem.png",
    "鉄の欠片":         "img/materials/ironShard.png",
    "魔鉄の核":         "img/materials/magicIronCore.png",
    "雷鳥の羽":         "img/materials/thunderFeather.png",
    "不死鳥の核":       "img/materials/phoenixCore.png",

    // 転生3
    "影の短剣":         "img/materials/shadowDagger.png",
    "虚無の刃":         "img/materials/voidBlade.png",
    "悪魔の角":         "img/materials/demonHorn.png",
    "魔王の核":         "img/materials/demonKingCore.png",
    "水晶の鱗":         "img/materials/crystalScale.png",
    "虹色の結晶":       "img/materials/rainbowCrystal.png",
    "巨神の骨":         "img/materials/titanBone.png",
    "神話の石":         "img/materials/mythStone.png",
    "魔女の杖":         "img/materials/witchStaff.png",
    "禁忌の魔書":       "img/materials/forbiddenBook.png",
    "死霊の指":         "img/materials/undeadFinger.png",
    "魂の宝珠":         "img/materials/soulOrb.png",
    "地獄犬の牙":       "img/materials/hellhoundFang.png",
    "冥府の炎":         "img/materials/infernoFlame.png",
    "グリフィンの羽":   "img/materials/griffinWing.png",
    "聖なる羽根":       "img/materials/holyFeather.png",
    "死霊術の書":       "img/materials/necromancyBook.png",
    "禁断の魔法陣":     "img/materials/forbiddenCircle.png",
    "魔神の核":         "img/materials/demonCore.png",
    "魔神の心臓":       "img/materials/demonHeart.png",

    // 転生4
    "混沌の鱗":         "img/materials/chaosScale.png",
    "混沌の核":         "img/materials/chaosCore.png",
    "虚無の欠片":       "img/materials/voidShard.png",
    "虚空の結晶":       "img/materials/voidCrystal.png",
    "魂の破片":         "img/materials/soulShard.png",
    "魂喰いの宝珠":     "img/materials/soulEaterOrb.png",
    "世界蛇の鱗":       "img/materials/worldScale.png",
    "神代の牙":         "img/materials/divFang.png",
    "堕天使の羽":       "img/materials/fallenWing.png",
    "聖なる涙":         "img/materials/holyTear.png",
    "時の砂":           "img/materials/timeSand.png",
    "時空の結晶":       "img/materials/spacetimeCrystal.png",
    "古代の呪符":       "img/materials/ancientCharm.png",
    "封印の宝珠":       "img/materials/sealedOrb.png",
    "魔鋼の欠片":       "img/materials/demonicSteelShard.png",
    "悪魔の核":         "img/materials/demonCoreB.png",
    "深淵の結晶":       "img/materials/abyssCrystal.png",
    "奈落の核":         "img/materials/abyssCore.png",
    "神滅の鱗":         "img/materials/godSlayerScale.png",
    "神滅龍の心臓":     "img/materials/godSlayerHeart.png"

  };

  return paths[name] || null;

}
